### ISSUE TITLE
偶尔出现的bug

### ISSUE THREAD

**Issue by ccflyy** [AriaLyy/Aria#609]
java.lang.ArrayIndexOutOfBoundsException
length=8192; index=8192
## 版本
* 框架版本
3.8.5

## 错误日志

com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
--
2 com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
3 com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
4 com.android.okhttp.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
5 com.android.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
6 com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:593)
7 com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
8 com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
9 com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
10 com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
11 com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
12 com.dlna.coolcast.download.util.HttpRequestUtil.java.net.URLConnection sendGetRequest(java.lang.String,java.util.Map,java.util.Map)(HttpRequestUtil.java:133)
13 com.dlna.coolcast.download.util.HttpRequestUtil.java.net.URLConnection sendGetRequest(java.lang.String)(HttpRequestUtil.java:144)
14 com.dlna.coolcast.download.DownloadManager$M3u8DownloadTaskThread$3.boolean downloadFile(java.lang.String,java.lang.String)(DownloadManager.java:385)
15 com.dlna.coolcast.download.DownloadManager$M3u8DownloadTaskThread$3.void run()(DownloadManager.java:369)
16 java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
请提供下完整的日志，我看你发的日志并不是我打印的

**Comment by wlf2008win** [comment]
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
2    at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
3    at com.android.okhttp.HttpUrl.percentDecode(HttpUrl.java:1517)
4    at com.android.okhttp.HttpUrl.percentDecode(HttpUrl.java:1500)
5    at com.android.okhttp.HttpUrl.percentDecode(HttpUrl.java:1506)
6    at com.android.okhttp.HttpUrl.<init>(HttpUrl.java:314)
7    at com.android.okhttp.HttpUrl.<init>(Unknown Source:0)
8    at com.android.okhttp.HttpUrl$Builder.build(HttpUrl.java:916)
9    at com.android.okhttp.HttpUrl.getChecked(HttpUrl.java:634)
10    at com.android.okhttp.OkHttpClient$1.getHttpUrlChecked(OkHttpClient.java:112)
11    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:347)
12    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:332)
13    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:124)
14    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
15    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
16    at com.networkbench.agent.impl.instrumentation.NBSHttpsURLConnectionExtension.connect(Unknown Source:5)
17    at com.arialyy.aria.m3u8.M3U8InfoTask.run(Unknown Source:49)
18    at com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(Unknown Source:11)
19    at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(Unknown Source:29)
20    at com.arialyy.aria.core.loader.AbsNormalLoader.run(Unknown Source:38)
21    at java.lang.Thread.run(Thread.java:764)
